on: push

jobs:
  uikit-only-tests:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install xcbeautify
      - run: |
          cd UIKit-Example
          xcodebuild test \
            -project TestAppDelegateExample.xcodeproj \
            -scheme TestAppDelegateExample \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro' -sdk iphonesimulator \
            | xcbeautify
