on: push
env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

jobs:
  uikit-only-tests:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Install xcbeautify
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/thii/xcbeautify
          version: '*'
      - name: UIKit Example Tests
        run: |
          cd UIKit-Example
          xcodebuild test \
            -project TestAppDelegateExample.xcodeproj \
            -scheme TestAppDelegateExample \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro' -sdk iphonesimulator # | xcbeautify

  swiftui-only-tests:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Install xcbeautify
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/thii/xcbeautify
          version: '*'
      - name: SwiftUI Example Tests
        run: |
          cd SwiftUI-Example
          xcodebuild test \
            -project TestAppExample.xcodeproj \
            -scheme TestAppExample \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro' -sdk iphonesimulator # | xcbeautify


  swiftui-wit-uikit-only-tests:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Install xcbeautify
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/thii/xcbeautify
          version: '*'
      - name: Mixed SwiftUI and UIKit Example Tests
        run: |
          cd Mixed-SwiftUI-UIKit-Example
          xcodebuild test \
            -project MixedSwiftUIUIKitExample.xcodeproj \
            -scheme MixedSwiftUIUIKitExample \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro' -sdk iphonesimulator # | xcbeautify
